server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: kevintam
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
mybatis-plus:
  #    configuration:
  #      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value:  0 #逻辑未删除
      logic-delete-field: 1 #逻辑已删
  mapper-locations: classpath:mapper/*Mapper.xml